name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  # Temporary commented out until fixed
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version-file: ".nvmrc"
  #         cache: "yarn"
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile --prefer-offline
  #     - name: Run tests
  #       run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run linter
        run: yarn lint

  publish_main_image:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      # Temporary commented out until fixed
      # - test
      - lint
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push to Ghcr
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/devterm-its/semantic_pull_requests:main
          push: true
